# server port
server.port=9099

# session config
server.servlet.session.timeout=7200

# servlet config
server.servlet.context-path=/dpline/

# time zone

spring.jackson.time-zone=GMT+8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=dolphinscheduler
spring.datasource.password=dolphinscheduler
spring.datasource.url=jdbc:mysql://10.250.12.80:3306/dpline?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8


# file size limit for upload
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
# enable response compression
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
server.undertow.max-http-post-size=5000000

# Authentication types (supported types: PASSWORD)
security.authentication.type=PASSWORD

mybatis-plus.mapper-locations=classpath:mapper/*.xml
#枚举
mybatis-plus.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumOrdinalTypeHandler

# minio 的参数
spring.messages.basename=i18n/sprMesgs

#============================================================================
# LDAP Config
# mock ldap server from https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/
#============================================================================
# admin userId
#security.authentication.ldap.user.admin=read-only-admin
# ldap server config
#ldap.urls=ldap://ldap.forumsys.com:389/
#ldap.base.dn=dc=example,dc=com
#ldap.username=cn=read-only-admin,dc=example,dc=com
#ldap.password=password
#ldap.user.identity.attribute=uid
#ldap.user.email.attribute=mail
